server:
  port: 4001

redis:
  cache:
    expiration: 3600

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root #ENC(rC/X/8UBBH2bn9Tgfuu7aw==)
    password: 123456 #ENC(IVTzs5LDfVEsblAFWFgA9w==)
    url: jdbc:mysql://127.0.0.1:3306/fw-cloud-pay?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest #ENC(tbrYcuNRFv1gflhdhpuY0g==)
    password: guest #ENC(tbrYcuNRFv1gflhdhpuY0g==)
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 1.0

logging:
  config: classpath:logback.xml

